### ISSUE TITLE
Should we include alteration hooks provided by Atomium in this module ?

### ISSUE THREAD

**Issue by drupol** [drupol/registryonsteroids#10]
Atomium theme implements a couple of alter hook to extend the '#theme' member of render arrays. (see: https://github.com/ec-europa/atomium/tree/7.x-2.x/atomium/includes/alter)

In forms, entities, blocks, etc etc...

I think it would be better to include this in a module.

Should we include them ?

**Comment by donquixote** [comment]
These are the essential part of this functionality, or not?
Without that, the new theme hooks won't be called.

Is there any reason someone might want the registry altering, but not the render array altering to replace #theme and #theme_wrappers?
If so, we could make two distinct modules. If not, it can be all in one module.

**Comment by drupol** [comment]
Fixed.
