### ISSUE TITLE
Dependency missing for menu_*() functions

### ISSUE THREAD

**Issue by piotrsmykaj** [drupol/registryonsteroids#153]
As the `registryonsteroids_alter` module using `menu_get_menus()` function and other `menu_*()` functions, there should be added `menu` dependency as the very minimal drupal instance with enabled of `registryonsteroids_alter` returns error like this:

`Fatal error: Call to undefined function menu_get_menus() in /sites/all/modules/contrib/registryonsteroids/modules/registryonsteroids_alter/registryonsteroids_alter.alter.inc on line 114`

**Comment by donquixote** [comment]
Maybe it is better to detect if menu module is enabled, and if not, simply skip the menu-related functionality?

**Comment by drupol** [comment]
PR has been submitted, waiting for a review before merging.

Feel free to test it and give some feedback to speed up the process.

Thanks for using Registry on steroids!

**Comment by piotrsmykaj** [comment]
Thank you guys. Features of this module sounds very nice as a addition for the Drupal core. Nice! 👍
