### ISSUE TITLE
warning: ignoring broken ref refs/remotes/origin/HEAD

### ISSUE THREAD

**Issue by donquixote** [drupol/registryonsteroids#28]
I got this when trying `git lol 26-` and then hitting TAB for autocomplete.

> git checkout 26-warning: ignoring broken ref refs/remotes/origin/HEAD

I think this might be because `master` branch was deleted on github, but HEAD was still on master there.
For now I re-added a master branch.
Maybe this can be changed in repository settings, which I do not have access to.

**Comment by drupol** [comment]
7.x-1.x is now the main branch.

**Comment by donquixote** [comment]
ok thanks!
