### ISSUE TITLE
Is README.md correct about core behavior?

### ISSUE THREAD

**Issue by donquixote** [drupol/registryonsteroids#44]
## What does README.md say?
In README.md, the section "Details" starts by describing the default core behavior:

From this text, I would assume that by default Drupal will call [HOOK]_preprocess_node__page_full() and [HOOK]_preprocess_node(), but not [HOOK]_preprocess_node__page().

## What happens instead?

Instead, I find that it only calls [HOOK]_preprocess_node(), and none of the two others.

## Steps to reproduce:

Using admin theme "seven".
Adding functions to `themes/seven/template.php`:

```php
function seven_preprocess_node(array &$vars) {
  dpm(__FUNCTION__);
}

function seven_preprocess_node__page(array &$vars) {
  dpm(__FUNCTION__);
}

function seven_preprocess_node__page__full(array &$vars) {
  dpm(__FUNCTION__);
}
```
Do NOT enable registryonsteroids module (or disable the theme registry alter hook).
Rebuild theme registry to let Drupal detect the new functions.

Run this code in `/devel/php` (node/43 is of type "page" on my test site)
```php
$node = node_load(43);
dpm($node, '$node');
$element = node_view($node);
dpm($element);
$element['#theme'] = 'node__page__full';
drupal_render($element);
```

## Conclusion
It seems that, by default, Drupal never executes any variant theme (pre)processors. It only ever executes the (pre)processors from the base hook.

Maybe this changes if the variant is explicitly registered with hook_theme()?
It doesn't say that in the README.md.

@drupol Can you explain?

**Comment by drupol** [comment]
You are perfectly right.

![screenshot-127 0 0 1-8888-2018 03 14-08-47-01](https://user-images.githubusercontent.com/252042/37389362-58c0be1c-2764-11e8-8297-3f8f49340374.png)

I will do a small update to the README.md accordingly to this.

**Comment by drupol** [comment]
Hi,

The PR #45 is ready to review.
