### ISSUE TITLE
Template suggestions don't need this module, or do they?

### ISSUE THREAD

**Issue by donquixote** [drupol/registryonsteroids#94]
The module page https://www.drupal.org/project/registryonsteroids and the README.md say this:

> And it will also provides multiple templates suggestions:
> 
> - node--page--full.tpl.php
> - node--page.tpl.php
> - node.tpl.php

Is this not misleading? 
In most cases, those template suggestions will already work without this module. Only the extra preprocess functions are added.

**Comment by drupol** [comment]
Indeed, the way it is written is a bit misleading, I will update accordingly tomorrow.

**Comment by drupol** [comment]
It's ready for review again.
