### ISSUE TITLE
Ensure registryonsteroids module is run the last 

### ISSUE THREAD

**Issue by drupol** [drupol/registryonsteroids#96]
The hook_module_implements_alter() can be runned before or after some modules, depending on their weight.

We must ensure that the weight of ROS is the heaviest.

This issue/pr implements the hook_enable() with a weight update.

**Comment by donquixote** [comment]
Are you aware of other modules which try to put their own hook_theme_registry_alter() first or last?

**Comment by drupol** [comment]
Most of the module are adding their own changes first or last.
In any case, if the module is heavier than ROS, then it will cause issues for sure.

E.g:

* Create 2 modules: aaa and zzz
* Implements:
```
/**
 * Implements hook_module_implements_alter().
 *
 * @param mixed[] $implementations
 *   Format: $[$module] = $group
 * @param string $hook
 */
function [MODULENAME]_module_implements_alter(array &$implementations, $hook) {
  if ('theme_registry_alter' === $hook) {
    /* @see _registryonsteroids_first_theme_registry_alter() */
    $implementations = array('_[MODULE_NAME]_first' => FALSE) + $implementations;

    /* @see _registryonsteroids_last_theme_registry_alter() */
    $implementations['_[MODULE_NAME]_last'] = FALSE;
  }

  if (function_exists('krumo') && 'theme_registry_alter' == $hook) {
    krumo(__FUNCTION__);
    krumo($hook);
    krumo($implementations);
  }
}

```
* Clear the cache

You'll see that if this PR is not committed, there might be some inconsistencies.

**Comment by donquixote** [comment]
> In any case, if the module is heavier than ROS, then it will cause issues for sure.

Only if the module uses hook_module_implements_alter() AND hook_theme_registry_alter().
It would be interesting to see such a module.

**Comment by drupol** [comment]
Yes indeed, but I guess there are some other module implementing this ?

**Comment by donquixote** [comment]
Just thinking the other modules might have reasons why they also want to
run last? I bet registryonsteroids has the "better reasons", but it would
still be interesting to see an example.

**Comment by drupol** [comment]
TBH, I have none in mind, I just came into this edge case while explaining the module to someone :-)

**Comment by drupol** [comment]
I've updated the commit. The updated module's weight is calculated using the max(weight) of the system table, then adding +1.
